##`1.` **데이터 로드**

구글 드라이브를 마운트하고 특정 폴더로 이동

In [ ]:
from google.colab import drive
import os

# 구글 드라이브 마운트
drive.mount('/content/drive')

# 특정 폴더로 이동
folder_path = '/content/drive/MyDrive/Colab Notebooks/IBAS ALPHA/data/치매안심병원_프로젝트'
os.chdir(folder_path)
print("Current working directory: ", os.getcwd())

Mounted at /content/drive
Current working directory:  /content/drive/MyDrive/Colab Notebooks/IBAS ALPHA/data/치매안심병원_프로젝트

CSV 파일 2개와 XLSX 파일 1개를 불러오고 각 파일의 형태를 확인

In [ ]:
import pandas as pd

# CSV 파일 로드
df_main = pd.read_csv('보건복지부_시군구별 치매현황_20231231.csv', encoding='euc-kr')
df_alone = pd.read_csv('독거노인가구비율_시도_시_군_구__2022.csv', encoding='euc-kr')
df_basicPension = pd.read_csv('한국사회보장정보원_복지사업 시군구별 수급권자 현황_20231231.csv', encoding='euc-kr')

# XLSX 파일 로드 (모든 시트 한 번에 로드)
all_sheets = pd.read_excel('2023_노인시설_총괄표(시.군.구)_최종.xlsx', sheet_name=None)

# 각 시트를 개별 데이터프레임으로 분리
df_resWelfar = all_sheets['3. 가.노인주거복지시설 총괄표(시･군･구)']
df_medWelfar = all_sheets['나. 노인의료복지시설 총괄표(시･군･구)']
df_leisWelfar = all_sheets['다. 노인여가복지시설 총괄표(시･군･구)']
df_homeEldWelfar = all_sheets['라. 재가노인복지시설 총괄표(시･군･구)']
df_demenWelfar = all_sheets['사. 치매전담형 장기요양기관 총괄표(시･군･구)']

In [ ]:
# CSV 전처리

# 열 이름 변경
new_column_names = {
    '행정구역별' : '행정구역',
    '2022': '독거노인가구비율',
    '2022.1': '노인1인가구(65)',
    '2022.2': '전체일반가구'
}

df_alone = df_alone.rename(columns=new_column_names)

# 상위 4개 행 삭제
df_alone = df_alone.drop(index=[0])

In [ ]:
df_basicPension = df_basicPension[df_basicPension['사업명'] == '기초연금']

In [ ]:
# XLSX 시트 전처리

# 열 이름 변경
new_column_names = {
    '가. 노인주거복지시설 총괄표(시･군･구)' : '시도',
    'Unnamed: 1': '노인인구(65)',
    'Unnamed: 2': '계_시설수',
    'Unnamed: 3': '계_정원(분양)',
    'Unnamed: 4': '계_현원(입주)',
    'Unnamed: 5': '계_종사자수',
    'Unnamed: 6': '양로시설_시설수',
    'Unnamed: 7': '양로시설_정원(분양)',
    'Unnamed: 8': '양로시설_현원(입주)',
    'Unnamed: 9': '양로시설_종사자수',
    'Unnamed: 10': '노인공동생활가정_시설수',
    'Unnamed: 11': '노인공동생활가정_정원(분양)',
    'Unnamed: 12': '노인공동생활가정_현원(입주)',
    'Unnamed: 13': '노인공동생활가정_종사자수',
    'Unnamed: 14': '노인복지주택_시설수',
    'Unnamed: 15': '노인복지주택_정원(분양)',
    'Unnamed: 16': '노인복지주택_현원(입주)',
    'Unnamed: 17': '노인복지주택_종사자수'
}

df_resWelfar = df_resWelfar.rename(columns=new_column_names)

# 상위 4개 행 삭제
df_resWelfar = df_resWelfar.drop(index=[0, 1, 2, 3])

In [ ]:
# XLSX 시트 전처리

# 열 이름 변경
new_column_names = {
    '나. 노인의료복지시설 총괄표(시･군･구)' : '시도',
    'Unnamed: 1': '노인인구(65)',
    'Unnamed: 2': '계_시설수',
    'Unnamed: 3': '계_정원(분양)',
    'Unnamed: 4': '계_현원(입주)',
    'Unnamed: 5': '계_종사자수',
    'Unnamed: 6': '노인요양시설_시설수',
    'Unnamed: 7': '노인요양시설_정원(분양)',
    'Unnamed: 8': '노인요양시설_현원(입주)',
    'Unnamed: 9': '노인요양시설_종사자수',
    'Unnamed: 10': '노인요양공동생활가정_시설수',
    'Unnamed: 11': '노인요양공동생활가정_정원(분양)',
    'Unnamed: 12': '노인요양공동생활가정_현원(입주)',
    'Unnamed: 13': '노인요양공동생활가정_종사자수'
}

df_medWelfar = df_medWelfar.rename(columns=new_column_names)

# 상위 4개 행 삭제
df_medWelfar = df_medWelfar.drop(index=[0, 1, 2, 3])

In [ ]:
# XLSX 시트 전처리

# 열 이름 변경
new_column_names = {
    '다. 노인여가복지시설 총괄표(시･군･구)' : '시도',
    'Unnamed: 1': '노인인구(65)',
    'Unnamed: 2': '합계',
    'Unnamed: 3': '노인복지관_시설수',
    'Unnamed: 4': '노인복지관_종사자수',
    'Unnamed: 5': '경로당',
    'Unnamed: 6': '노인교실'
}

df_leisWelfar = df_leisWelfar.rename(columns=new_column_names)

# 상위 4개 행 삭제
df_leisWelfar = df_leisWelfar.drop(index=[0, 1, 2])

In [ ]:
# XLSX 시트 전처리

# 열 이름 변경
new_column_names = {
    '라. 재가노인복지시설 총괄표(시･군･구)' : '시도',
    'Unnamed: 1': '노인인구(65)',
    'Unnamed: 2': '계_시설수',
    'Unnamed: 3': '계_정원',
    'Unnamed: 4': '계_현원',
    'Unnamed: 5': '계_종사자수',
    'Unnamed: 6': '단기보호_시설수',
    'Unnamed: 7': '단기보호_정원',
    'Unnamed: 8': '단기보호_현원',
    'Unnamed: 9': '단기보호_종사자수',
    'Unnamed: 10': '방문간호_시설수',
    'Unnamed: 11': '방문간호_정원',
    'Unnamed: 12': '방문간호_현원',
    'Unnamed: 13': '방문간호_종사자수',
    'Unnamed: 14': '방문목욕_시설수',
    'Unnamed: 15': '방문목욕_정원',
    'Unnamed: 16': '방문목욕_현원',
    'Unnamed: 17': '방문목욕_종사자수',
    'Unnamed: 18': '방문요양_시설수',
    'Unnamed: 19': '방문요양_정원',
    'Unnamed: 20': '방문요양_현원',
    'Unnamed: 21': '방문요양_종사자수',
    'Unnamed: 22': '복지용구지원_시설수',
    'Unnamed: 23': '복지용구지원_정원',
    'Unnamed: 24': '복지용구지원_현원',
    'Unnamed: 25': '복지용구지원_종사자수',
    'Unnamed: 26': '재가노인지원_시설수',
    'Unnamed: 27': '재가노인지원_정원',
    'Unnamed: 28': '재가노인지원_현원',
    'Unnamed: 29': '재가노인지원_종사자수',
    'Unnamed: 30': '주야간보호_시설수',
    'Unnamed: 31': '주야간보호_정원',
    'Unnamed: 32': '주야간보호_현원',
    'Unnamed: 33': '주야간보호_종사자수'
}

df_homeEldWelfar = df_homeEldWelfar.rename(columns=new_column_names)

# 상위 4개 행 삭제
df_homeEldWelfar = df_homeEldWelfar.drop(index=[0, 1, 2, 3])

In [ ]:
# XLSX 시트 전처리

# 열 이름 변경
new_column_names = {
    '사. 치매전담형 장기요양기관 총괄표(시･군･구)' : '시도',
    'Unnamed: 1': '계_시설수',
    'Unnamed: 2': '계_정원',
    'Unnamed: 3': '계_현원',
    'Unnamed: 4': '계_종사자_계',
    'Unnamed: 5': '계_종사자_요양보호사',
    'Unnamed: 6': '계_종사자_프로그램관리자',
    'Unnamed: 7': '주･야간보호_시설수',
    'Unnamed: 8': '주･야간보호_정원',
    'Unnamed: 9': '주･야간보호_현원',
    'Unnamed: 10': '주･야간보호_종사자_계',
    'Unnamed: 11': '주･야간보호_종사자_요양보호사',
    'Unnamed: 12': '주･야간보호_종사자_프로그램관리자',
    'Unnamed: 13': '전담실_시설수',
    'Unnamed: 14': '전담실_정원',
    'Unnamed: 15': '전담실_현원',
    'Unnamed: 16': '전담실_종사자_계',
    'Unnamed: 17': '전담실_종사자_요양보호사',
    'Unnamed: 18': '전담실_종사자_프로그램관리자',
    'Unnamed: 19': '공동가정_시설수',
    'Unnamed: 20': '공동가정_정원',
    'Unnamed: 21': '공동가정_현원',
    'Unnamed: 22': '공동가정_종사자_계',
    'Unnamed: 23': '공동가정_종사자_요양보호사',
    'Unnamed: 24': '공동가정_종사자_프로그램관리자',
}

df_demenWelfar = df_demenWelfar.rename(columns=new_column_names)

# 상위 4개 행 삭제
df_demenWelfar = df_demenWelfar.drop(index=[0, 1, 2, 3])

##`2.` **데이터 확인**

In [ ]:
df_main.head()

,연도,시도,시군구,성별,연령별,노인인구수,치매환자수,치매환자유병률,최경도 환자,경도 환자,중등도 환자,중증 환자,알츠하이머 환자수,알츠하이머 환자유병률,혈관성치매 환자수,혈관성치매 환자유병률,기타 환자환자수,기타 환자유병률,경도인지장애 환자수,경도인지장애 환자유병률
0,2020,전국,전국,전체,60~64세,3804709.5,23350.26,0.61,4062.95,9667.01,6001.02,3619.29,0.00,0.00,23350.26,0.61,0.00,0.00,568975.71,14.95
1,2020,전국,전국,전체,65~69세,2635592.0,36620.52,1.39,6371.97,15160.90,9411.47,5676.18,34204.14,1.30,0.00,0.00,2416.38,0.09,472079.05,17.91
2,2020,전국,전국,전체,70~74세,2000708.5,77236.58,3.86,13439.16,31975.94,19849.80,11971.67,74101.52,3.70,1868.56,0.09,1279.71,0.06,432263.10,21.61
3,2020,전국,전국,전체,75~79세,1602662.5,189626.57,11.83,32995.02,78505.40,48734.03,29392.12,79081.82,4.93,36835.05,2.30,73617.65,4.59,238681.35,14.89
4,2020,전국,전국,전체,80~84세,1110911.5,232892.50,20.96,40523.30,96417.50,59853.37,36098.34,182257.11,16.41,8518.04,0.77,42047.60,3.78,530714.37,47.77

In [ ]:
df_alone.head()

    행정구역 독거노인가구비율 노인1인가구(65)    전체일반가구
1     전국      9.1    1973416  21773507
2  서울특별시      7.5     309072   4098818
3    종로구      8.5       5501     64422
4     중구      9.7       5448     56260
5    용산구      7.3       7222     98483

In [ ]:
df_basicPension.head()

       사업명     기준년월     시도  시군구  수급권자수  수급가구수
2052  기초연금  2023-12  서울특별시  종로구  14447  11603
2053  기초연금  2023-12  서울특별시   중구  14734  12019
2054  기초연금  2023-12  서울특별시  용산구  16099  13072
2055  기초연금  2023-12  서울특별시  성동구  24162  19192
2056  기초연금  2023-12  서울특별시  광진구  28780  22693

In [ ]:
df_resWelfar.head()

,시도,노인인구(65),계_시설수,계_정원(분양),계_현원(입주),계_종사자수,양로시설_시설수,양로시설_정원(분양),양로시설_현원(입주),양로시설_종사자수,노인공동생활가정_시설수,노인공동생활가정_정원(분양),노인공동생활가정_현원(입주),노인공동생활가정_종사자수,노인복지주택_시설수,노인복지주택_정원(분양),노인복지주택_현원(입주),노인복지주택_종사자수
4,서울 합계,1658207,23,2962,2590,534,9,1156,869,207,3,27,18,9,11,1779,1703,318
5,종로구,27704,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,중구,24660,2,242,242,62,0,0,0,0,0,0,0,0,2,242,242,62
7,용산구,38478,1,114,83,15,0,0,0,0,0,0,0,0,1,114,83,15
8,성동구,47530,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_medWelfar.head()

,시도,노인인구(65),계_시설수,계_정원(분양),계_현원(입주),계_종사자수,노인요양시설_시설수,노인요양시설_정원(분양),노인요양시설_현원(입주),노인요양시설_종사자수,노인요양공동생활가정_시설수,노인요양공동생활가정_정원(분양),노인요양공동생활가정_현원(입주),노인요양공동생활가정_종사자수
4,서울 합계,1658207,491,16055,14237,10054,229,13729,12118,8470,262,2326,2119,1584
5,종로구,27704,9,356,332,236,8,347,324,229,1,9,8,7
6,중구,24660,3,83,75,68,2,74,66,62,1,9,9,6
7,용산구,38478,4,203,199,141,3,194,190,134,1,9,9,7
8,성동구,47530,8,456,408,281,4,420,372,256,4,36,36,25

In [ ]:
df_leisWelfar.head()

      시도 노인인구(65)    합계 노인복지관_시설수 노인복지관_종사자수   경로당 노인교실
3  서울 합계  1658207  3868        36       2057  3490  342
4    종로구    27704    73         2        154    62    9
5     중구    24660    54         1         67    50    3
6    용산구    38478   110         1         48    89   20
7    성동구    47530   177         1         68   164   12

In [ ]:
df_homeEldWelfar.head()

,시도,노인인구(65),계_시설수,계_정원,계_현원,계_종사자수,단기보호_시설수,단기보호_정원,단기보호_현원,단기보호_종사자수,...,복지용구지원_현원,복지용구지원_종사자수,재가노인지원_시설수,재가노인지원_정원,재가노인지원_현원,재가노인지원_종사자수,주야간보호_시설수,주야간보호_정원,주야간보호_현원,주야간보호_종사자수
4,서울 합계,1658207,1878,14629,39483,33582,23,249,205,113,...,2626,62,18,0,2342,97,457,14380,12243,5517
5,종로구,27704,20,102,428,260,0,0,0,0,...,31,1,1,0,131,5,5,102,88,58
6,중구,24660,26,203,679,360,0,0,0,0,...,0,0,1,0,164,4,6,203,177,87
7,용산구,38478,21,139,395,181,0,0,0,0,...,0,0,1,0,153,4,6,139,134,68
8,성동구,47530,43,360,625,476,1,9,9,10,...,0,16,0,0,0,0,13,351,312,157

In [ ]:
df_demenWelfar.head()

,시도,계_시설수,계_정원,계_현원,계_종사자_계,계_종사자_요양보호사,계_종사자_프로그램관리자,주･야간보호_시설수,주･야간보호_정원,주･야간보호_현원,...,전담실_현원,전담실_종사자_계,전담실_종사자_요양보호사,전담실_종사자_프로그램관리자,공동가정_시설수,공동가정_정원,공동가정_현원,공동가정_종사자_계,공동가정_종사자_요양보호사,공동가정_종사자_프로그램관리자
4,서울 합계,47,694,614,329,278,51,19,333,267,...,324,201,178,23,3,23,23,18,13,5
5,종로구,1,20,19,7,6,1,1,20,19,...,0,0,0,0,0,0,0,0,0,0
6,중구,1,16,9,4,3,1,1,16,9,...,0,0,0,0,0,0,0,0,0,0
7,용산구,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,성동구,5,85,78,43,39,4,1,21,15,...,63,33,32,1,0,0,0,0,0,0

In [ ]:
# from google.colab import files

# # 데이터프레임을 CSV 파일로 저장
# df_alone.to_csv('df_alone.csv', index=False, encoding='utf-8-sig')
# df_resWelfar.to_csv('df_resWelfar.csv', index=False, encoding='utf-8-sig')
# df_medWelfar.to_csv('df_medWelfar.csv', index=False, encoding='utf-8-sig')
# df_leisWelfar.to_csv('df_leisWelfar.csv', index=False, encoding='utf-8-sig')
# df_homeEldWelfar.to_csv('df_homeEldWelfar.csv', index=False, encoding='utf-8-sig')
# df_demenWelfar.to_csv('df_demenWelfar.csv', index=False, encoding='utf-8-sig')

# # CSV 파일 로컬로 다운로드
# files.download('df_alone.csv')
# files.download('df_resWelfar.csv')
# files.download('df_medWelfar.csv')
# files.download('df_leisWelfar.csv')
# files.download('df_homeEldWelfar.csv')
# files.download('df_demenWelfar.csv')

##`3.` **데이터 전처리**

In [ ]:
# 제외할 '시군구' 값 목록
exclude_values = [
    '전국', '서울특별시', '부산광역시', '인천광역시', '대구광역시', '광주광역시', '대전광역시', '울산광역시',
    '세종특별자치시', '경기도', '충청북도', '충청남도', '전라남도', '전라북도', '경상북도',
    '경상남도', '강원도', '제주특별자치도'
]

# '시군구' 값이 exclude_values에 포함되지 않은 행만 남김
df_main = df_main[~df_main['시군구'].isin(exclude_values)]

# '시도' 열에서 '전국' 값을 가진 행을 삭제
df_main = df_main[df_main['시도'] != '전국']

# '시도' 값에 따라 '시군구' 값에 추가할 접두어 정의
prefixes = {
    '서울특별시': '서울_',
    '부산광역시': '부산_',
    '대구광역시': '대구_',
    '인천광역시': '인천_',
    '광주광역시': '광주_',
    '대전광역시': '대전_',
    '울산광역시': '울산_',
    '경기도': '경기_',
    '강원도': '강원_',
    '충청북도': '충북_',
    '충청남도': '충남_',
    '전라북도': '전북_',
    '전라남도': '전남_',
    '경상북도': '경북_',
    '경상남도': '경남_',
    '세종특별자치시' : '세종_',
    '제주특별자치도': '제주_'
}

# '시도' 값에 따라 '시군구' 값에 접두어 추가
df_main['시군구'] = df_main.apply(lambda row: prefixes[row['시도']] + row['시군구'], axis=1)

In [ ]:
# 조건에 맞는 데이터 추출
condition = (df_main['성별'] == '여') & (df_main['연령별'] == '65세이상') & (df_main['연도'] == 2023)
female_elderly_population = df_main[condition][['시군구', '노인인구수']]

# 새로운 열 '여성노인인구수' 추가
df_main = df_main.merge(female_elderly_population, on='시군구', how='left', suffixes=('', '_여성노인인구수'))

# '여성노인인구수' 열 이름 수정
df_main = df_main.rename(columns={'노인인구수_여성노인인구수': '여성노인인구수'})

# # 조건에 맞는 행에서만 '여성노인인구수' 열 값을 업데이트하고 나머지는 NaN으로 유지
# df_main['여성노인인구수'] = df_main.apply(
#     lambda row: row['여성노인인구수'] if row['성별'] == '여' and row['연령별'] == '65세이상' and row['연도'] == 2023 else None, axis=1
# )


# 조건에 맞는 행 필터링
filtered_df_main = df_main[(df_main['연도'] == 2023) &
                           ((df_main['성별'] == '전체')) &
                           (df_main['연령별'] == '65세이상')]


# 선택된 열만 포함하는 데이터프레임 생성
selected_columns = ['시도', '시군구', '노인인구수', '여성노인인구수', '치매환자수', '치매환자유병률', '중증 환자', '경도인지장애 환자수', '경도인지장애 환자유병률']
final_df_main = filtered_df_main[selected_columns]

In [ ]:
final_df_main

,시도,시군구,노인인구수,여성노인인구수,치매환자수,치매환자유병률,중증 환자,경도인지장애 환자수,경도인지장애 환자유병률
18727,서울특별시,서울_종로구,27661.5,15238.5,3127.29,11.31,484.73,6419.92,23.21
18751,서울특별시,서울_중구,24713.5,13792.0,2662.26,10.77,412.65,5671.50,22.95
18775,서울특별시,서울_용산구,38033.0,21471.5,4249.27,11.17,658.64,8782.64,23.09
18799,서울특별시,서울_성동구,47964.0,26850.5,4889.99,10.20,757.95,10951.29,22.83
18823,서울특별시,서울_광진구,54690.5,30211.0,5323.19,9.73,825.09,12342.12,22.57
...,...,...,...,...,...,...,...,...,...
24847,경상남도,경남_함양군,13862.0,8250.0,1849.62,13.34,286.69,3377.37,24.36
24871,경상남도,경남_거창군,18249.5,10798.0,2391.68,13.11,370.71,4396.00,24.09
24895,경상남도,경남_합천군,17754.5,10569.0,2438.95,13.74,378.04,4368.69,24.61
24919,제주특별자치도,제주_제주시,78665.0,44550.5,8700.38,11.06,1348.56,17855.19,22.70
24943,제주특별자치도,제주_서귀포시,39036.0,22031.0,4531.17,11.61,702.33,9013.33,23.09

### B. 독거노인 데이터 전처리

In [ ]:
# 선택된 두 개의 열만 포함하는 데이터프레임 생성
selected_columns = ['행정구역', '독거노인가구비율']
final_df_alone = df_alone[selected_columns]

new_column_names = {
    '행정구역': '시군구',
    '독거노인가구비율': '독거노인가구비율'
}

# 열 이름 변경
final_df_alone = final_df_alone.rename(columns=new_column_names)

In [ ]:
# 시도와 접두어 매핑
prefixes = {
    '서울특별시': '서울_',
    '부산광역시': '부산_',
    '대구광역시': '대구_',
    '인천광역시': '인천_',
    '광주광역시': '광주_',
    '대전광역시': '대전_',
    '울산광역시': '울산_',
    '경기도': '경기_',
    '강원도': '강원_',
    '충청북도': '충북_',
    '충청남도': '충남_',
    '전라북도': '전북_',
    '전라남도': '전남_',
    '경상북도': '경북_',
    '경상남도': '경남_',
    '세종특별자치시' : '세종_',
    '제주특별자치도': '제주_'
}

# 접두어를 추가하는 함수
def add_prefix(row, current_prefix):
    if row['시군구'] in prefixes:
        current_prefix[0] = prefixes[row['시군구']]
        return row['시군구']
    elif current_prefix[0] != '':
        return current_prefix[0] + row['시군구']
    else:
        return row['시군구']

# 초기 접두어
current_prefix = ['']

# 데이터프레임의 '시군구' 열 업데이트
final_df_alone['시군구'] = final_df_alone.apply(add_prefix, axis=1, current_prefix=current_prefix)

# 수정된 데이터프레임 출력
final_df_alone

         시군구 독거노인가구비율
1         전국      9.1
2      서울특별시      7.5
3     서울_종로구      8.5
4      서울_중구      9.7
5     서울_용산구      7.3
..       ...      ...
242   경남_거창군     19.1
243   경남_합천군     26.9
244  제주특별자치도      8.0
245   제주_제주시      7.4
246  제주_서귀포시      9.6

[246 rows x 2 columns]

### C. 기초노령연금 데이터 전처리

In [ ]:
# '시도', '시군구', '수급권자수', '수급가구수' 열만 남기기
df_basicPension = df_basicPension[['시도', '시군구', '수급권자수', '수급가구수']]

# '시도' 값에 따라 '시군구' 값에 추가할 접두어 정의
prefixes = {
    '서울특별시': '서울_',
    '부산광역시': '부산_',
    '대구광역시': '대구_',
    '인천광역시': '인천_',
    '광주광역시': '광주_',
    '대전광역시': '대전_',
    '울산광역시': '울산_',
    '경기도': '경기_',
    '강원특별자치도': '강원_',
    '충청북도': '충북_',
    '충청남도': '충남_',
    '전라북도': '전북_',
    '전라남도': '전남_',
    '경상북도': '경북_',
    '경상남도': '경남_',
    '세종특별자치시' : '세종_',
    '제주특별자치도': '제주_'
}

# '시도' 값에 따라 '시군구' 값에 접두어 추가
df_basicPension['시군구'] = df_basicPension.apply(lambda row: prefixes[row['시도']] + row['시군구'], axis=1)

# '시도' 열 삭제
final_df_basicPension = df_basicPension.drop(columns=['시도'])

# 열 이름 변경
final_df_basicPension = final_df_basicPension.rename(columns={
    '수급권자수': '기초연금_수급권자수',
    '수급가구수': '기초연금_수급가구수'
})

final_df_basicPension

<ipython-input-24-5570980c6f14>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_basicPension['시군구'] = df_basicPension.apply(lambda row: prefixes[row['시도']] + row['시군구'], axis=1)

         시군구  기초연금_수급권자수  기초연금_수급가구수
2052  서울_종로구       14447       11603
2053   서울_중구       14734       12019
2054  서울_용산구       16099       13072
2055  서울_성동구       24162       19192
2056  서울_광진구       28780       22693
...      ...         ...         ...
2297  강원_화천군        4724        3635
2298  강원_양구군        4046        3133
2299  강원_인제군        5488        4305
2300  강원_고성군        6914        5457
2301  강원_양양군        6852        5319

[250 rows x 3 columns]

### C. 노인복지시설 데이터 전처리

In [ ]:
# 선택된 두 개의 열만 포함하는 데이터프레임 생성
selected_columns = ['시도', '계_시설수', '계_정원(분양)', '계_종사자수']
final_df_resWelfar = df_resWelfar[selected_columns]

new_column_names = {
    '시도': '시군구',
    '계_시설수': '노인주거복지시설 수',
    '계_정원(분양)' : '노인주거복지시설 정원',
    '계_종사자수' : '노인주거복지시설 종사자수'
}

# 열 이름 변경
final_df_resWelfar = final_df_resWelfar.rename(columns=new_column_names)

In [ ]:
# 접두어 사전
prefixes = {
    '서울 합계': '서울_',
    '부산 합계': '부산_',
    '대구 합계': '대구_',
    '인천 합계': '인천_',
    '광주 합계': '광주_',
    '대전 합계': '대전_',
    '울산 합계': '울산_',
    '경기 합계': '경기_',
    '강원 합계': '강원_',
    '충북 합계': '충북_',
    '충남 합계': '충남_',
    '전북 합계': '전북_',
    '전남 합계': '전남_',
    '경북 합계': '경북_',
    '경남 합계': '경남_',
    '세종 합계': '세종_',
    '제주 합계': '제주_'
}

# 접두어를 추가하는 함수
def add_prefix(row, current_prefix):
    if row['시군구'] in prefixes:
        current_prefix[0] = prefixes[row['시군구']]
        return row['시군구']
    elif current_prefix[0] != '':
        return current_prefix[0] + row['시군구']
    else:
        return row['시군구']

# 초기 접두어
current_prefix = ['']

# 데이터프레임의 '시군구' 열 업데이트
final_df_resWelfar['시군구'] = final_df_resWelfar.apply(add_prefix, axis=1, current_prefix=current_prefix)

# 수정된 데이터프레임 출력
final_df_resWelfar

         시군구 노인주거복지시설 수 노인주거복지시설 정원 노인주거복지시설 종사자수
4      서울 합계         23        2962           534
5     서울_종로구          0           0             0
6      서울_중구          2         242            62
7     서울_용산구          1         114            15
8     서울_성동구          0           0             0
..       ...        ...         ...           ...
245   경남_거창군          0           0             0
246   경남_합천군          0           0             0
247    제주 합계          2          90            30
248   제주_제주시          2          90            30
249  제주_서귀포시          0           0             0

[246 rows x 4 columns]

In [ ]:
# 선택된 두 개의 열만 포함하는 데이터프레임 생성
selected_columns = ['시도', '계_시설수', '계_정원(분양)', '계_종사자수']
final_df_medWelfar = df_medWelfar[selected_columns]

new_column_names = {
    '시도': '시군구',
    '계_시설수': '노인의료복지시설 수',
    '계_정원(분양)' : '노인의료복지시설 정원',
    '계_종사자수' : '노인의료복지시설 종사자수'
}

# 열 이름 변경
final_df_medWelfar = final_df_medWelfar.rename(columns=new_column_names)

In [ ]:
# 접두어 사전
prefixes = {
    '서울 합계': '서울_',
    '부산 합계': '부산_',
    '대구 합계': '대구_',
    '인천 합계': '인천_',
    '광주 합계': '광주_',
    '대전 합계': '대전_',
    '울산 합계': '울산_',
    '경기 합계': '경기_',
    '강원 합계': '강원_',
    '충북 합계': '충북_',
    '충남 합계': '충남_',
    '전북 합계': '전북_',
    '전남 합계': '전남_',
    '경북 합계': '경북_',
    '경남 합계': '경남_',
    '세종 합계': '세종_',
    '제주 합계': '제주_'
}

# 접두어를 추가하는 함수
def add_prefix(row, current_prefix):
    if row['시군구'] in prefixes:
        current_prefix[0] = prefixes[row['시군구']]
        return row['시군구']
    elif current_prefix[0] != '':
        return current_prefix[0] + row['시군구']
    else:
        return row['시군구']

# 초기 접두어
current_prefix = ['']

# 데이터프레임의 '시군구' 열 업데이트
final_df_medWelfar['시군구'] = final_df_medWelfar.apply(add_prefix, axis=1, current_prefix=current_prefix)

# 수정된 데이터프레임 출력
final_df_medWelfar

         시군구 노인의료복지시설 수 노인의료복지시설 정원 노인의료복지시설 종사자수
4      서울 합계        491       16055         10054
5     서울_종로구          9         356           236
6      서울_중구          3          83            68
7     서울_용산구          4         203           141
8     서울_성동구          8         456           281
..       ...        ...         ...           ...
245   경남_거창군          8         394           228
246   경남_합천군          6         517           260
247    제주 합계         70        4032          2287
248   제주_제주시         49        2842          1586
249  제주_서귀포시         21        1190           701

[246 rows x 4 columns]

In [ ]:
# 선택된 두 개의 열만 포함하는 데이터프레임 생성
selected_columns = ['시도', '합계']
final_df_leisWelfar = df_leisWelfar[selected_columns]

new_column_names = {
    '시도': '시군구',
    '합계' : '노인여가복지시설 수'
}

# 열 이름 변경
final_df_leisWelfar = final_df_leisWelfar.rename(columns=new_column_names)

In [ ]:
# 접두어 사전
prefixes = {
    '서울 합계': '서울_',
    '부산 합계': '부산_',
    '대구 합계': '대구_',
    '인천 합계': '인천_',
    '광주 합계': '광주_',
    '대전 합계': '대전_',
    '울산 합계': '울산_',
    '경기 합계': '경기_',
    '강원 합계': '강원_',
    '충북 합계': '충북_',
    '충남 합계': '충남_',
    '전북 합계': '전북_',
    '전남 합계': '전남_',
    '경북 합계': '경북_',
    '경남 합계': '경남_',
    '세종 합계': '세종_',
    '제주 합계': '제주_'
}

# 접두어를 추가하는 함수
def add_prefix(row, current_prefix):
    if row['시군구'] in prefixes:
        current_prefix[0] = prefixes[row['시군구']]
        return row['시군구']
    elif current_prefix[0] != '':
        return current_prefix[0] + row['시군구']
    else:
        return row['시군구']

# 초기 접두어
current_prefix = ['']

# 데이터프레임의 '시군구' 열 업데이트
final_df_leisWelfar['시군구'] = final_df_leisWelfar.apply(add_prefix, axis=1, current_prefix=current_prefix)

# 수정된 데이터프레임 출력
final_df_leisWelfar

         시군구 노인여가복지시설 수
3      서울 합계       3868
4     서울_종로구         73
5      서울_중구         54
6     서울_용산구        110
7     서울_성동구        177
..       ...        ...
244   경남_거창군        439
245   경남_합천군        528
246    제주 합계        493
247   제주_제주시        328
248  제주_서귀포시        165

[246 rows x 2 columns]

In [ ]:
# 선택된 두 개의 열만 포함하는 데이터프레임 생성
selected_columns = ['시도', '계_시설수', '계_정원', '계_종사자수']
final_df_homeEldWelfar = df_homeEldWelfar[selected_columns]

new_column_names = {
    '시도': '시군구',
    '계_시설수': '재가노인복지시설 수',
    '계_정원' : '재가노인복지시설 정원',
    '계_종사자수' : '재가노인복지시설 종사자수'
}

# 열 이름 변경
final_df_homeEldWelfar = final_df_homeEldWelfar.rename(columns=new_column_names)

In [ ]:
# 접두어 사전
prefixes = {
    '서울 합계': '서울_',
    '부산 합계': '부산_',
    '대구 합계': '대구_',
    '인천 합계': '인천_',
    '광주 합계': '광주_',
    '대전 합계': '대전_',
    '울산 합계': '울산_',
    '경기 합계': '경기_',
    '강원 합계': '강원_',
    '충북 합계': '충북_',
    '충남 합계': '충남_',
    '전북 합계': '전북_',
    '전남 합계': '전남_',
    '경북 합계': '경북_',
    '경남 합계': '경남_',
    '세종 합계': '세종_',
    '제주 합계': '제주_'
}

# 접두어를 추가하는 함수
def add_prefix(row, current_prefix):
    if row['시군구'] in prefixes:
        current_prefix[0] = prefixes[row['시군구']]
        return row['시군구']
    elif current_prefix[0] != '':
        return current_prefix[0] + row['시군구']
    else:
        return row['시군구']

# 초기 접두어
current_prefix = ['']

# 데이터프레임의 '시군구' 열 업데이트
final_df_homeEldWelfar['시군구'] = final_df_homeEldWelfar.apply(add_prefix, axis=1, current_prefix=current_prefix)

# 수정된 데이터프레임 출력
final_df_homeEldWelfar

         시군구 재가노인복지시설 수 재가노인복지시설 정원 재가노인복지시설 종사자수
4      서울 합계       1878       14629         33582
5     서울_종로구         20         102           260
6      서울_중구         26         203           360
7     서울_용산구         21         139           181
8     서울_성동구         43         360           476
..       ...        ...         ...           ...
245   경남_거창군         33         199             0
246   경남_합천군         20         116           238
247    제주 합계        101         611          1024
248   제주_제주시         81         413           802
249  제주_서귀포시         20         198           222

[246 rows x 4 columns]

In [ ]:
# 선택된 두 개의 열만 포함하는 데이터프레임 생성
selected_columns = ['시도', '계_시설수', '계_정원', '계_종사자_계']
final_df_demenWelfar = df_demenWelfar[selected_columns]

new_column_names = {
    '시도': '시군구',
    '계_시설수': '치매전담형 장기요양기관 수',
    '계_정원' : '치매전담형 장기요양기관 정원',
    '계_종사자_계' : '치매전담형 장기요양기관 종사자수'
}

# 열 이름 변경
final_df_demenWelfar = final_df_demenWelfar.rename(columns=new_column_names)

# 하위 2개 행 삭제
final_df_demenWelfar = final_df_demenWelfar.drop(final_df_demenWelfar.tail(2).index)

In [ ]:
# 접두어 사전
prefixes = {
    '서울 합계': '서울_',
    '부산 합계': '부산_',
    '대구 합계': '대구_',
    '인천 합계': '인천_',
    '광주 합계': '광주_',
    '대전 합계': '대전_',
    '울산 합계': '울산_',
    '경기 합계': '경기_',
    '강원 합계': '강원_',
    '충북 합계': '충북_',
    '충남 합계': '충남_',
    '전북 합계': '전북_',
    '전남 합계': '전남_',
    '경북 합계': '경북_',
    '경남 합계': '경남_',
    '세종 합계': '세종_',
    '제주 합계': '제주_'
}

# 접두어를 추가하는 함수
def add_prefix(row, current_prefix):
    if row['시군구'] in prefixes:
        current_prefix[0] = prefixes[row['시군구']]
        return row['시군구']
    elif current_prefix[0] != '':
        return current_prefix[0] + row['시군구']
    else:
        return row['시군구']

# 초기 접두어
current_prefix = ['']

# 데이터프레임의 '시군구' 열 업데이트
final_df_demenWelfar['시군구'] = final_df_demenWelfar.apply(add_prefix, axis=1, current_prefix=current_prefix)

# 수정된 데이터프레임 출력
final_df_demenWelfar

         시군구 치매전담형 장기요양기관 수 치매전담형 장기요양기관 정원 치매전담형 장기요양기관 종사자수
4      서울 합계             47             694               329
5     서울_종로구              1              20                 7
6      서울_중구              1              16                 4
7     서울_용산구              0               0                 0
8     서울_성동구              5              85                43
..       ...            ...             ...               ...
245   경남_거창군              1              16                 0
246   경남_합천군              1              25                 8
247    제주 합계              9             136                56
248   제주_제주시              6              88                39
249  제주_서귀포시              3              48                17

[246 rows x 4 columns]

##`4.` **조인**

In [ ]:
## 아직 시군구 열의 전처리 미완

# 데이터프레임들을 '시군구'를 기준으로 조인
final_df = final_df_main.merge(final_df_alone, on='시군구', how='left')
final_df = final_df.merge(final_df_basicPension, on='시군구', how='left')
final_df = final_df.merge(final_df_resWelfar, on='시군구', how='left')
final_df = final_df.merge(final_df_medWelfar, on='시군구', how='left')
final_df = final_df.merge(final_df_leisWelfar, on='시군구', how='left')
final_df = final_df.merge(final_df_homeEldWelfar, on='시군구', how='left')
final_df = final_df.merge(final_df_demenWelfar, on='시군구', how='left')

# 최종 조인된 데이터프레임 출력
final_df

,시도,시군구,노인인구수,여성노인인구수,치매환자수,치매환자유병률,중증 환자,경도인지장애 환자수,경도인지장애 환자유병률,독거노인가구비율,...,노인의료복지시설 수,노인의료복지시설 정원,노인의료복지시설 종사자수,노인여가복지시설 수,재가노인복지시설 수,재가노인복지시설 정원,재가노인복지시설 종사자수,치매전담형 장기요양기관 수,치매전담형 장기요양기관 정원,치매전담형 장기요양기관 종사자수
0,서울특별시,서울_종로구,27661.5,15238.5,3127.29,11.31,484.73,6419.92,23.21,8.5,...,9,356,236,73,20,102,260,1,20,7
1,서울특별시,서울_중구,24713.5,13792.0,2662.26,10.77,412.65,5671.50,22.95,9.7,...,3,83,68,54,26,203,360,1,16,4
2,서울특별시,서울_용산구,38033.0,21471.5,4249.27,11.17,658.64,8782.64,23.09,7.3,...,4,203,141,110,21,139,181,0,0,0
3,서울특별시,서울_성동구,47964.0,26850.5,4889.99,10.20,757.95,10951.29,22.83,7.0,...,8,456,281,177,43,360,476,5,85,43
4,서울특별시,서울_광진구,54690.5,30211.0,5323.19,9.73,825.09,12342.12,22.57,6.3,...,19,588,359,106,45,508,484,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,경상남도,경남_함양군,13862.0,8250.0,1849.62,13.34,286.69,3377.37,24.36,23.2,...,9,484,258,412,21,165,167,1,16,0
256,경상남도,경남_거창군,18249.5,10798.0,2391.68,13.11,370.71,4396.00,24.09,19.1,...,8,394,228,439,33,199,0,1,16,0
257,경상남도,경남_합천군,17754.5,10569.0,2438.95,13.74,378.04,4368.69,24.61,26.9,...,6,517,260,528,20,116,238,1,25,8
258,제주특별자치도,제주_제주시,78665.0,44550.5,8700.38,11.06,1348.56,17855.19,22.70,7.4,...,49,2842,1586,328,81,413,802,6,88,39
259,제주특별자치도,제주_서귀포시,39036.0,22031.0,4531.17,11.61,702.33,9013.33,23.09,9.6,...,21,1190,701,165,20,198,222,3,48,17

치매안심병원 기존 존재하는 시군구 리스트 :   
서울_은평구, 경기_부천시, 인천_서구, 인천_계양구, 대전_유성구, 충북_제천시, 충남_서산시, 충남_홍성군, 경북_안동시, 경북_김천시, 경북_상주시, 경북_경산시, 울산_울주군, 광주_광산구, 전북_군산시, 전북_전주시, 전남_화순군, 제주_제주시

In [ ]:
# 확인할 문자열 리스트
target_strings = [
    '인천_서구', '인천_계양구', '대전_유성구', '충북_제천시', '충남_서산시', '충남_홍성군',
    '경북_안동시', '경북_김천시', '경북_상주시', '경북_경산시', '울산_울주군', '광주_광산구',
    '전북_군산시', '전북_전주시', '전남_화순군', '제주_제주시', '경기_부천시', '서울_은평구'
]

# 새로운 열 '치매안심병원 유무' 추가하고 초기값을 0으로 설정
final_df['치매안심병원 유무'] = 0

# '시군구' 열의 값이 target_strings에 포함되는 경우 '치매안심병원 유무' 열의 값을 1로 설정
final_df.loc[final_df['시군구'].isin(target_strings), '치매안심병원 유무'] = 1

# 수정된 데이터프레임 출력
final_df

,시도,시군구,노인인구수,여성노인인구수,치매환자수,치매환자유병률,중증 환자,경도인지장애 환자수,경도인지장애 환자유병률,독거노인가구비율,...,노인의료복지시설 정원,노인의료복지시설 종사자수,노인여가복지시설 수,재가노인복지시설 수,재가노인복지시설 정원,재가노인복지시설 종사자수,치매전담형 장기요양기관 수,치매전담형 장기요양기관 정원,치매전담형 장기요양기관 종사자수,치매안심병원 유무
0,서울특별시,서울_종로구,27661.5,15238.5,3127.29,11.31,484.73,6419.92,23.21,8.5,...,356,236,73,20,102,260,1,20,7,0
1,서울특별시,서울_중구,24713.5,13792.0,2662.26,10.77,412.65,5671.50,22.95,9.7,...,83,68,54,26,203,360,1,16,4,0
2,서울특별시,서울_용산구,38033.0,21471.5,4249.27,11.17,658.64,8782.64,23.09,7.3,...,203,141,110,21,139,181,0,0,0,0
3,서울특별시,서울_성동구,47964.0,26850.5,4889.99,10.20,757.95,10951.29,22.83,7.0,...,456,281,177,43,360,476,5,85,43,0
4,서울특별시,서울_광진구,54690.5,30211.0,5323.19,9.73,825.09,12342.12,22.57,6.3,...,588,359,106,45,508,484,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,경상남도,경남_함양군,13862.0,8250.0,1849.62,13.34,286.69,3377.37,24.36,23.2,...,484,258,412,21,165,167,1,16,0,0
256,경상남도,경남_거창군,18249.5,10798.0,2391.68,13.11,370.71,4396.00,24.09,19.1,...,394,228,439,33,199,0,1,16,0,0
257,경상남도,경남_합천군,17754.5,10569.0,2438.95,13.74,378.04,4368.69,24.61,26.9,...,517,260,528,20,116,238,1,25,8,0
258,제주특별자치도,제주_제주시,78665.0,44550.5,8700.38,11.06,1348.56,17855.19,22.70,7.4,...,2842,1586,328,81,413,802,6,88,39,1
259,제주특별자치도,제주_서귀포시,39036.0,22031.0,4531.17,11.61,702.33,9013.33,23.09,9.6,...,1190,701,165,20,198,222,3,48,17,0

In [ ]:
# 제거할 '시군구' 값 목록
remove_values = [
    '경기_수원시 장안구', '경기_수원시 권선구', '경기_수원시 팔달구', '경기_수원시 영통구',
    '경기_성남시 수정구', '경기_성남시 중원구', '경기_성남시 분당구', '경기_안양시 만안구',
    '경기_안양시 동안구', '경기_안산시 상록구', '경기_안산시 단원구', '경기_고양시 덕양구',
    '경기_고양시 일산동구', '경기_고양시 일산서구', '경기_용인시 처인구', '경기_용인시 기흥구',
    '경기_용인시 수지구', '충북_청주시 상당구', '충북_청주시 서원구', '충북_청주시 흥덕구',
    '충북_청주시 청원구', '충남_천안시 동남구', '충남_천안시 서북구', '전북_전주시 완산구',
    '전북_전주시 덕진구', '경북_포항시 남구', '경북_포항시 북구', '경남_통합창원시 의창구',
    '경남_통합창원시 성산구', '경남_통합창원시 마산합포구', '경남_통합창원시 마산회원구', '경남_통합창원시 진해구', '경남_통합창원시'
]

# '시군구' 값이 remove_values에 포함되지 않은 행만 남김
final_df = final_df[~final_df['시군구'].isin(remove_values)]

In [ ]:
# 각 열별로 결측치의 개수 확인
missing_values_count = final_df.isnull().sum()

# 결측치의 개수를 출력
missing_values_count

시도                    0
시군구                   0
노인인구수                 0
여성노인인구수               0
치매환자수                 0
치매환자유병률               0
중증 환자                 0
경도인지장애 환자수            0
경도인지장애 환자유병률          0
독거노인가구비율             32
기초연금_수급권자수           11
기초연금_수급가구수           11
노인주거복지시설 수            0
노인주거복지시설 정원           0
노인주거복지시설 종사자수         0
노인의료복지시설 수            0
노인의료복지시설 정원           0
노인의료복지시설 종사자수         0
노인여가복지시설 수            0
재가노인복지시설 수            0
재가노인복지시설 정원           0
재가노인복지시설 종사자수         0
치매전담형 장기요양기관 수        0
치매전담형 장기요양기관 정원       0
치매전담형 장기요양기관 종사자수     0
치매안심병원 유무             0
dtype: int64

In [ ]:
# from google.colab import files

# # 데이터프레임을 CSV 파일로 저장
# final_df.to_csv('final_df.csv', index=False, encoding='utf-8-sig')


# # CSV 파일 로컬로 다운로드
# files.download('final_df.csv')